- hosts: sbdb
  become: yes
  become_user: root
  vars_prompt:
    # - name: Ipaddress.stdout
    #   prompt: what is mysql Private ipaddress
    #   private: no
    - name: Domainname
      prompt: what is Domian name
      private: no   
    - name: cloudstack
      prompt: what is cloudstack server IP
      private: no       
  tasks:

   - name: Install supporting Packages
     package:
       name: java-11-openjdk-devel
       state: present 

   - name: Get the server IP address
     command: curl http://checkip.amazonaws.com
     register: pubipaddress   

   - name: Get the server IP address
     shell: hostname -I | awk '{print $1}'
     register: Ipaddress   

   - name: get the msql details
     copy:
       src: /root/{{item}}
       dest: /tmp/
     with_items:
       - Password-{{Ipaddress.stdout}}-zabbix
       - Password-{{Ipaddress.stdout}}-wolf
       - Password-{{Ipaddress.stdout}}-monogo
       - Password-{{Ipaddress.stdout}}

   - name: Download requried files
     get_url:
       url: '{{item}}'
       dest: /root/
     with_items:
         - https://sp-poc.s3.amazonaws.com/other-files/bsahrc.txt
         - https://sp-poc.s3.amazonaws.com/other-files/EncryptionUtil.class
         - https://sp-poc.s3.amazonaws.com/other-files/EncryptionUtil.java

       

   - name: Get the Zabbix Admin password
     command: cat /root/Password-{{Ipaddress.stdout}}/Password-{{Ipaddress.stdout}}-zabbixadmin
     register: zabbix_Admin_pass       

   - name: Get the password monogo details
     command: cat /tmp/Password-{{Ipaddress.stdout}}-monogo
     register: monogo

   - name: Get the password zabbix details
     command: cat /root/Password-{{Ipaddress.stdout}}/Password-{{Ipaddress.stdout}}-rabbitmq
     register: rabbitpass

   - name: Get the password zabbix details
     command: cat /root/Password-{{Ipaddress.stdout}}/Password-{{Ipaddress.stdout}}-zabbix_stackbill_pass
     register: zabbix_stackbill_pass

   - name: Get the password wolf details
     command: cat /tmp/Password-{{Ipaddress.stdout}}-wolf
     register: wolf

   - name: Get the password zabbix details
     command: cat /tmp/Password-{{Ipaddress.stdout}}-zabbix
     register: zabbix

   - name: Encrypted password
     shell: java EncryptionUtil {{zabbix_stackbill_pass.stdout}}  bt/dLcRhhK/LYdTchNXxsQ== | head -n 1
     register: Encrypted_stack_bill     

   - name: Get the Ip address
     command: cat /tmp/Password-{{Ipaddress.stdout}}
     register: ip

   - name: Replace the credentails
     replace:
       path: /root/bsahrc.txt
       regexp: "{{item.find}}"
       replace: "{{item.replace}}"
     with_items:       
       - {find: 'wolfpass', replace: '{{wolf.stdout}}' }
       - {find: 'wolfmonpass', replace: '{{monogo.stdout}}' }
       - {find: 'rabbitpass', replace: '{{rabbitpass.stdout}}' }
       - {find: '10.61.61.2', replace: '{{Ipaddress.stdout}}' }
       - {find: 'my.domain.com', replace: '{{Domainname}}' }  
       - {find: '185.95.215.18', replace: '{{pubipaddress.stdout}}' }     
       - {find: '10.30.11.7850', replace: '{{cloudstack}}' }
       - {find: 'rabbitip', replace: '{{Ipaddress.stdout}}' }
       - {find: 'WOLF_MONGO_HOST=localhost', replace: 'WOLF_MONGO_HOST={{Ipaddress.stdout}}' }
       - {find: 'WOLF_DB_HOST=localhost', replace: 'WOLF_DB_HOST={{Ipaddress.stdout}}' }
       - {find: 'ab22996b80e4fb373de9ec995ac5f3ed', replace: '{{Encrypted_stack_bill.stdout}}' }


   - name: copy the content to bashrc    
     shell: cat /root/bsahrc.txt >> /root/.bashrc

   - name: Password file
     shell: echo "{{Encrypted_stack_bill.stdout}}"  >> /root/Password-{{Ipaddress.stdout}}/Password-{{Ipaddress.stdout}}-Encrypted_stack_bill     

   - name: Password file
     shell: echo "{{Domainname}}"  >> /root/Password-{{Ipaddress.stdout}}/Password-{{Ipaddress.stdout}}-Domainname     

   - name: Password file
     shell: echo "{{cloudstack}}"  >> /root/Password-{{Ipaddress.stdout}}/Password-{{Ipaddress.stdout}}-cloudstackip 

   - name: Copy password file
     fetch:
        src: /root/Password-{{Ipaddress.stdout}}/{{item}}
        dest: /root/
        flat: yes
     with_items:
       - Password-{{Ipaddress.stdout}}-Encrypted_stack_bill 
       - Password-{{Ipaddress.stdout}}-Domainname
       - Password-{{Ipaddress.stdout}}-cloudstackip 