- hosts: sbcore
  become: yes
  become_user: root
  tasks:
   - name: Disable SELinux
     selinux:
       state: disabled

   - name: Disable and Stop Firewall
     service:
       name: firewalld
       state: stopped
       enabled: False
     
   - name: Install supporting Packages
     package:
       name:
         - wget
         - epel-release
         - lsof
         - nc
         - telnet
       state: present 
    
   - name: Download jdk-11
     get_url:
       url: https://sp-poc.s3.amazonaws.com/Java/jdk-11.0.15.1.tar.gz
       dest: /opt

   - name: Download jdk-8u
     get_url:
       url: https://sp-poc.s3.amazonaws.com/Java/jdk-8u221-linux-x64.tar.gz
       dest: /opt

   - name: Download  Java.sh
     get_url:
       url: https://sp-poc.s3.amazonaws.com/Java/java.sh
       dest: /etc/profile.d/

   - name: Extract jdk-11 into /opt
     unarchive:
       src: /opt/jdk-11.0.15.1.tar.gz
       dest: /opt/
       remote_src: yes

   - name: Extract jdk-8u into /opt
     unarchive:
       src: /opt/jdk-8u221-linux-x64.tar.gz
       dest: /opt/
       remote_src: yes

   - name: Execute the java script
     command: sh /etc/profile.d/java.sh

   - name: Set variables
     shell: source /etc/profile.d/java.sh

   - name: Create a symbolic
     file:
       src: /opt/jdk1.8.0_221/bin/java
       dest: /usr/bin/java
       state: link

   - name:  View java version
     command: java -version
     register: java
    
   - debug:
       msg: '{{java}}'