- hosts: sbcore
  become: yes
  become_user: root
  vars_prompt:
      - name: Domainname
        prompt: what is Domian name
        private: no  
      - name: Ipaddress
        prompt: what is zabbix ip address
        private: no  
       
  tasks:
   - name: Disable SELinux
     selinux:
       state: disabled

   - name: get the msql details
     copy:
       src: /root/{{item}}
       dest: /tmp/
     with_items:
       - Password-{{Ipaddress}}

   - name: Install nginx
     package: 
      name:
        - epel-release
        - nginx
      state: present

   - name: Download Nginx conf
     get_url:
       url: https://sp-poc.s3.amazonaws.com/nginx.conf
       dest: /etc/nginx/conf.d/stackbill.conf

    - name: Replace the nginx conf
     replace:
       path: /etc/nginx/conf.d/stackbill.conf
       regexp: "{{item.find}}"
       replace: "{{item.replace}}"
     with_items:       
       - {find: 'app.thecloud.id', replace: '{{Domainname}}' }
       - {find: '10.98.99.12', replace: '{{Ipaddress}}' }
      #  - {find: 'rabbitpass', replace: '{{rabbitpass.stdout}}' }
      #  - {find: '10.61.61.2', replace: '{{Ipaddress.stdout}}' }
      #  - {find: 'my.domain.com', replace: '{{Domainname}}' }  
      #  - {find: '185.95.215.18', replace: '{{pubipaddress.stdout}}' }     
      #  - {find: '10.30.11.7850', replace: '{{cloudstack}}' }
      #  - {find: 'rabbitip', replace: '{{Ipaddress.stdout}}' }      


   - name: Restart nginx
     service:
       name: nginx
       state: started
       enabled: yes
