- hosts: centos2
  become: yes
  become_user: root
  tasks:
     - name: Update a new zabbix user
       community.zabbix.zabbix_user:
           server_url: "http://127.0.0.1/zabbix/"
           login_user: Admin
           login_password: 5TBmbwwHLtNKjEdM48mNPA==
           username: adminstackbill
           passwd: 5TBmbwwHLtNKjEdM48mNPA==
           usrgrps:
             - Zabbix administrators
             - Zabbix Super Admin	
           state: present