- hosts: mysql
  become: yes
  become_user: root
  tasks:
   - name: Disable SELinux
     selinux:
       state: disabled

   - name: Replace the yum.conf
     lineinfile:
       path:  /etc/yum.conf
       insertafter: EOF 
       line: sslverify=false 