- name: PhpMyAdmin Setup
  hosts: localhost
  tasks:
      - name: Restarting sshd
        shell: "sed -i 's/#Match User anoncvs/ForceCommand echo Please wait until the installation is completed..../g' /etc/ssh/sshd_config && systemctl restart sshd"

      - name: Updating Packages
        ansible.builtin.apt:
          update_cache: yes
         
      - debug:
         msg: "Installing Apache"

      - name: Installing apache
        apt:
          name: apache2
          state: latest

      - name: Removing site files
        file:
          path: "{{ item }}"
          state: absent
        with_items: 
          - /etc/apache2/sites-available/000-default.conf
          - /var/www/html/index.html

      - name: Copy files
        copy:
          src: "{{ item.confsrc }}"
          dest: "{{ item.confdest }}"
        with_items: 
          - { confsrc: '/usr/local/src/Apache-yaml/etc/apache2/sites-available/000-default.conf', confdest: '/etc/apache2/sites-available/'}
          - { confsrc: '/usr/local/src/Apache-yaml/var/www/html/index.html', confdest: '/var/www/html/'}

      - name: Starting service apache2
        service:
          name: apache2
          state: started 

      - name: Getting the status of the service
        shell: systemctl status apache2 | grep 'since'
        register: status

      - debug:
          var: status.stdout 

      - debug:
         msg: "Installing Mysql"

      - name: Installing mysql
        apt:
          name: mysql-server
          state: latest

      - name: Starting service mysql
        service:
          name: mysql
          state: started 

      - name: Getting the status of the service
        shell: systemctl status mysql | grep 'since'
        register: status

      - debug:
          var: status.stdout 

      - name: Generating root password
        shell: openssl rand -hex 24
        register: rootpassword

      - debug:
         var: rootpassword.stdout

      - name: Storing mysql password
        copy:
          dest: "/root/.mysql_root_password"
          content: |
            root_mysql_pass="{{ rootpassword.stdout }}"
      - name: Remove anonymous users
        command: 'mysql -ne "{{ item }}"'
        with_items:
          - DELETE FROM mysql.user WHERE User=''
        changed_when: False

      - name: Disallow root login remotely
        command: 'mysql -ne "{{ item }}"'
        with_items:
          - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
        changed_when: False

      - name: Remove test database and access to it
        command: 'mysql -ne "{{ item }}"'
        with_items:
          - DROP DATABASE IF EXISTS test
          - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
        changed_when: False

      - name: Reload privilege tables
        command: 'mysql -ne "{{ item }}"'
        with_items:
          - FLUSH PRIVILEGES
        changed_when: False

      - name: Alter Password
        shell: "{{ item }}"
        with_items:
          - mysql -n --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ rootpassword.stdout }}';"

      - debug:
          msg: "Mysql root password is stored under /root/.mysql_root_password"

      # - name: Change login type
      #   shell: 'mysql -u root -p{{ rootpassword.stdout }} -n --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH auth_socket;" > /dev/null 2>&1'

      - debug:
         msg: "Installing PHP"

      - name: Installation install software-properties-common
        apt: name=software-properties-common
      
      - name: "Repo PHP 8.1"
        apt_repository:
          repo="ppa:ondrej/php"
    
      - name: Installation PHP 8.1
        apt: name=php8.1 state=present

      - shell: php -v
        register: phpversion

      - debug:
          var: phpversion.stdout_lines 

      - name: Installing phpmyadmin & packages
        apt:
          name: ['phpmyadmin', 'php-mbstring', 'php-zip', 'php-gd', 'php-json', 'php-curl']
          state: latest

      - name: enable the PHP Mbstring extension
        shell: phpenmod mbstring

      - name: Download phpmyadmin files
        ansible.builtin.unarchive:
          src: https://files.phpmyadmin.net/phpMyAdmin/5.2.0/phpMyAdmin-5.2.0-all-languages.tar.gz
          dest: /usr/local/src/
          remote_src: yes
    
      - name: Rename a Existing folder & Move the latest Files
        shell: "{{ item }}"
        with_items:
          - 'mv /usr/share/phpmyadmin /usr/share/phpmyadmin.default'
          - 'mv /usr/local/src/phpMyAdmin-5.2.0-all-languages /usr/share/phpmyadmin'

      - name: Creating a tmp directory
        ansible.builtin.file:
          path: /usr/share/phpmyadmin/tmp
          state: directory
          mode: '0777'

      - name: Copy files for phpmyadmin
        copy:
          src: "{{ item.confsrc }}"
          dest: "{{ item.confdest }}"
        with_items: 
          - { confsrc: '/usr/local/src/Apache-yaml/etc/apache2/conf-enabled/phpmyadmin.conf', confdest: '/etc/apache2/conf-enabled/'}
          - { confsrc: '/usr/local/src/Apache-yaml/usr/share/phpmyadmin/.htaccess', confdest: '/usr/share/phpmyadmin/'}

      - name: Change ownership of a directory
        ansible.builtin.file:
          path: /usr/share/phpmyadmin
          state: directory
          recurse: yes
          owner: www-data
          group: www-data

      - name: Generating phpmyadmin password
        shell: openssl rand -hex 24
        register: phpmyadminpassword

      - debug:
         var: phpmyadminpassword.stdout

      - name: Storing mysql password
        copy:
         dest: "/root/.phpmyadmin_password"
         content: |
           phpmyadmin_pass="{{ phpmyadminpassword.stdout }}"
      - name: Configuring prompt
        shell: htpasswd -cb /etc/phpmyadmin/.htpasswd admin "{{ phpmyadminpassword.stdout }}"

      - name: Restart apache
        service:
           name: apache2
           state: restarted 

      - name: Restarting sshd
        shell: "sed -i 's/ForceCommand echo Please wait until the installation is completed..../#Match User anoncvs/g' /etc/ssh/sshd_config && systemctl restart sshd"
